name: Build and deploy Hugo app to Azure Web App - luffy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Zip artifact for deployment
        run: zip release.zip ./public -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: hugo-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: hugo-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7EEBED6BD13B4CF6AC6DD6A47114F867 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3081585AB0AA40A6AFD3106C4E3411AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7760B483144D4A32A845005395B1F01C }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'luffy'
          slot-name: 'Production'
          package: .
